[train] Fix maximum context length handling and generation tests after 0.16.0 upgrade (#1248)
# What does this PR do?

## Summary
Part 1 in resolving #1243 and #242

Fixes all the generation related tests (pause/ resume and weight syncing
related fixes are pending after this PR)

Fixes context length error message detection and some generation tests
after upgrade to vllm 0.16.0 in #1240 .

## Changes

### Context length errors

The error message when the model hit maximum context length has changed
a bit - vLLM now outputs something like;

> You passed 3148 input characters and requested 1000 output tokens.
However, the model's context length is only 1024 tokens, resulting in a
maximum input length of 24 tokens (at most 3072 characters). Please
reduce the length of the input prompt. (parameter=input_text,
value=3148)

I've changed the string matching logic in `vllm_engine.py` and the
assertions in the tests

### Import path errors

Also, some of the import paths were incorrect in the tests :

```bash
FAILED tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py::test_chat_completions - ModuleNotFoundError: No module named 'vllm.entrypoints.openai.protocol'
FAILED tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py::test_completions - ModuleNotFoundError: No module named 'vllm.entrypoints.openai.protocol'
```

The new paths are `vllm.entrypoints.openai.completion` and
`.chat_completion`


The following tests pass after this PR:

-
`tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py`
-
`tests/backends/skyrl_train/inference_engines/test_inference_engine_client.py`
<!-- devin-review-badge-begin -->

---

<a href="https://app.devin.ai/review/novasky-ai/skyrl/pull/1248"
target="_blank">
  <picture>
<source media="(prefers-color-scheme: dark)"
srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
<img
src="https://static.devin.ai/assets/gh-open-in-devin-review-light.svg?v=1"
alt="Open with Devin">
  </picture>
</a>
<!-- devin-review-badge-end -->

---------

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>