[chore] Set a default python version of 3.12  (#1710)
# What does this PR do?

Sets a default python version of 3.12 for the project. 

The SkyRL team currently tests on python 3.12 and many of our
dependencies are also explicitly configured for 3.12. See for example,
flash attention:
https://github.com/NovaSky-AI/SkyRL/blob/ccc181e27c04b9f02fe1f7d30483aad96902d7a5/pyproject.toml#L285

In pyproject.toml we only require a python version of 3.11 which means
that `uv` can end up selecting python 3.13 or 3.14 when users run SkyRL
with `uv run --extra fsdp ...` .

This leads to additional friction for users starting out with SkyRL
because some of the errors you get are pretty opaque:
1. If the python version selected by uv is 3.13, you will see vllm
initialization errors such as

```
(EngineCore pid=1422146) ERROR 05-27 18:12:26 [core.py:1136]     import flash_attn_2_cuda as flash_attn_gpu
(EngineCore pid=1422146) ERROR 05-27 18:12:26 [core.py:1136] ModuleNotFoundError: No module named 'flash_attn_2_cuda'
```
2. If the python version selected by uv is 3.14, then resolution for
`fsdp` extra can fail because ray doesn't support 3.14: `error:
Distribution `ray==2.51.1 @ registry+https://pypi.org/simple` can't be
installed because it doesn't have a source distribution or wheel for the
current platform`


This PR adds a `.python-version` file to the project so that the default
version selected is 3.12 :
https://docs.astral.sh/uv/concepts/python-versions/#python-versions

Users can still override and use a different python version if they
prefer, and uv will respect `pyproject.toml`:

```bash
sumanthrh@vm-rdma-6:~/recovered_files/fix-python-version$ uv run --isolated --extra fsdp -- python --version
      Built skyrl @ file:///home/sumanthrh/recovered_files/fix-python-version
      Built skyrl-gym @ file:///home/sumanthrh/recovered_files/fix-python-version/skyrl-gym
Installed 233 packages in 217ms
Python 3.12.13
sumanthrh@vm-rdma-6:~/recovered_files/fix-python-version$ uv run --isolated --extra fsdp --python 3.13  python --version
Installed 233 packages in 244ms
Python 3.13.13
sumanthrh@vm-rdma-6:~/recovered_files/fix-python-version$ uv run --isolated --extra fsdp --python 3.10  python --version
error: The requested interpreter resolved to Python 3.10.12, which is incompatible with the project's Python requirement: `>=3.11` (from `project.requires-python`)
```

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>