[Fix][CI] Fix CI Failures: set `return_dict=False` for sample API tests, use proper sleep/wake up for tests with colocated engine (#1463)
# What does this PR do?

Fixes CI failures for commit
https://github.com/NovaSky-AI/SkyRL/commit/bcf680f29626bccc725438d902281543e43e7215

Action:
https://github.com/NovaSky-AI/SkyRL/actions/runs/23986195029/job/69958423687


Failures:

```bash
=========================== short test summary info ============================
FAILED tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py::test_client_sample - aiohttp.client_exceptions.ClientResponseError: 400, message='2 validation errors:\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}\n\n  File "/home/ray/.cache/uv/builds-v0/.tmp5LDdf3/lib/python3.12/site-packages/vllm/entrypoints/utils.py", line 49, in generate\n    POST /inference/v1/generate [{\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}, {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}]', url='http://10.0.11.67:8080/inference/v1/generate'
FAILED tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py::test_client_sample_multiple - aiohttp.client_exceptions.ClientResponseError: 400, message='2 validation errors:\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}\n\n  File "/home/ray/.cache/uv/builds-v0/.tmp5LDdf3/lib/python3.12/site-packages/vllm/entrypoints/utils.py", line 49, in generate\n    POST /inference/v1/generate [{\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}, {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}]', url='http://10.0.11.67:8080/inference/v1/generate'
FAILED tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py::test_client_sample_deterministic - aiohttp.client_exceptions.ClientResponseError: 400, message='2 validation errors:\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}\n  {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}\n\n  File "/home/ray/.cache/uv/builds-v0/.tmp5LDdf3/lib/python3.12/site-packages/vllm/entrypoints/utils.py", line 49, in generate\n    POST /inference/v1/generate [{\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 0), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'input_ids\'}, {\'type\': \'int_parsing\', \'loc\': (\'body\', \'token_ids\', 1), \'msg\': \'Input should be a valid integer, unable to parse string as an integer\', \'input\': \'attention_mask\'}]', url='http://10.0.11.67:8080/inference/v1/generate'
FAILED tests/backends/skyrl_train/gpu/gpu_ci/test_inference_engine_client_http_endpoint.py::test_http_endpoint_openai_api_with_weight_sync - ray.exceptions.RayTaskError(OutOfMemoryError): [36mray::FSDPPolicyWorkerBase.init_model()[39m (pid=52843, ip=10.0.11.67, actor_id=02d1b5bb32ab2bff9eeac4242c000000, repr=<skyrl.backends.skyrl_train.workers.fsdp.fsdp_worker.FSDPPolicyWorkerBase object at 0x79726cb11010>)
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/workers/fsdp/fsdp_worker.py", line 197, in init_model
    self.model, self.optimizer, self.scheduler = strategy.prepare(
                                                 ^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 209, in prepare
    ret.append(self._fsdp_init_train_model(*arg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 288, in _fsdp_init_train_model
    fsdp_module = self._fsdp_init_model(model, is_train=True, is_wrapped=is_wrapped)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 278, in _fsdp_init_model
    fsdp2_load_full_state_dict(module, full_state, cpu_offload)
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_utils.py", line 365, in fsdp2_load_full_state_dict
    load_fsdp2_model_to_gpu(model)
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_utils.py", line 208, in load_fsdp2_model_to_gpu
    model.to(device, non_blocking=True)
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3587, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1381, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/distributed/fsdp/_fully_shard/_fully_shard.py", line 641, in _apply
    ret = super()._apply(*args, **kwargs)  # type: ignore[misc]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/nn/modules/module.py", line 933, in _apply
    module._apply(fn)
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/nn/modules/module.py", line 933, in _apply
    module._apply(fn)
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/nn/modules/module.py", line 964, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpHNg7Nb/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1367, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 520.00 MiB. GPU 0 has a total capacity of 21.95 GiB of which 247.50 MiB is free. Process 8821 has 318.00 MiB memory in use. Process 52492 has 15.81 GiB memory in use. Including non-PyTorch memory, this process has 5.56 GiB memory in use. Of the allocated memory 4.70 GiB is allocated by PyTorch, and 215.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
FAILED tests/backends/skyrl_train/gpu/gpu_ci/test_save_weights_for_sampler.py::test_save_weights_for_sampler_then_inference[colocate_fsdp2] - ray.exceptions.RayTaskError(OutOfMemoryError): [36mray::FSDPPolicyWorkerBase.init_model()[39m (pid=109704, ip=10.0.11.67, actor_id=12c5394f812536671322a94556000000, repr=<skyrl.backends.skyrl_train.workers.fsdp.fsdp_worker.FSDPPolicyWorkerBase object at 0x79dfd4fe9ac0>)
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/workers/fsdp/fsdp_worker.py", line 197, in init_model
    self.model, self.optimizer, self.scheduler = strategy.prepare(
                                                 ^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 209, in prepare
    ret.append(self._fsdp_init_train_model(*arg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 288, in _fsdp_init_train_model
    fsdp_module = self._fsdp_init_model(model, is_train=True, is_wrapped=is_wrapped)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_strategy.py", line 278, in _fsdp_init_model
    fsdp2_load_full_state_dict(module, full_state, cpu_offload)
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_utils.py", line 365, in fsdp2_load_full_state_dict
    load_fsdp2_model_to_gpu(model)
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2026-04-04_19-43-59_215328_3478/runtime_resources/working_dir_files/s3_anyscale-production-data-cld-hxkifz7xa22mwicp21nzkds1lw_org_xc6lv84h3d7m9dljcc17esfw2i_cld_hxkifz7xa22mwicp21nzkds1lw_runtime_env_packages_pkg_a772d5248d82a471ba25d418c175472f/skyrl/backends/skyrl_train/distributed/fsdp_utils.py", line 208, in load_fsdp2_model_to_gpu
    model.to(device, non_blocking=True)
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3587, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1381, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/distributed/fsdp/_fully_shard/_fully_shard.py", line 641, in _apply
    ret = super()._apply(*args, **kwargs)  # type: ignore[misc]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/nn/modules/module.py", line 933, in _apply
    module._apply(fn)
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/nn/modules/module.py", line 933, in _apply
    module._apply(fn)
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/nn/modules/module.py", line 964, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpTmtThw/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1367, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 520.00 MiB. GPU 0 has a total capacity of 21.95 GiB of which 209.50 MiB is free. Process 8821 has 356.00 MiB memory in use. Process 109368 has 15.81 GiB memory in use. Including non-PyTorch memory, this process has 5.56 GiB memory in use. Of the allocated memory 4.70 GiB is allocated by PyTorch, and 215.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
==== 5 failed, 118 passed, 36 deselected, 68 warnings in 8213.29s (2:16:53) ====
```


Fixes introduced:
1.
`tests/backends/skyrl_train/gpu/gpu_ci/inference_servers/test_new_inference_generation.py`:
Use `return_dict=False` to ensure that only token IDs are returned
2.
`tests/backends/skyrl_train/gpu/gpu_ci/test_inference_engine_client_http_endpoint.py::test_http_endpoint_openai_api_with_weight_sync`:
Fix sleep/wake up logic with colocated engine and policy workers
3.
`tests/backends/skyrl_train/gpu/gpu_ci/test_save_weights_for_sampler.py::test_save_weights_for_sampler_then_inference[colocate_fsdp2]`:
After #1387 , the engines are by default woken-up upon entering the
context manager `InferenceEngineState` - we need an explicit sleep in
this test to avoid OOM

---------

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>