[fix][CI] Fix tinker E2E CI runtime env conflicts (#1951)
# What does this PR do?

The Tinker E2E CI introduced in
https://github.com/NovaSky-AI/SkyRL/pull/1616 has been been failing with
the following error:

```bash
ValueError: Error retrieving result: Error code: 400 - {'detail': "Failed to merge the Job's runtime env .......} because of a conflict. Specifying the same runtime_env fields or the same environment variable keys is not allowed. Use RAY_OVERRIDE_JOB_RUNTIME_ENV=1 to instruct Ray to combine Job and Driver's runtime environment in the event of a conflict."} (status 400) for self.request_id='1' — exceeded 3 retries
```

The fix is to include `RAY_OVERRIDE_JOB_RUNTIME_ENV` in the job's
`env_vars` - we propagate `WANDB_API_KEY` explicitly in `ray.init` and
this conflicts with `WANDB_API_KEY` included in the job's runtime env.

I also added the env var `RAY_OVERRIDE_JOB_RUNTIME_ENV` in all the CI
YAMLs for consistency

---------

Signed-off-by: SumanthRH <sumanthrh@anyscale.com>
Co-authored-by: Claude Opus 4.8 (1M context) <noreply@anthropic.com>